services:
  web:
    build: .
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=demo
      - TZ=Asia/Shanghai
